# src/qa.py

from langchain_community.vectorstores import Chroma
from langchain_ollama import OllamaEmbeddings, OllamaLLM
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from live_data import detect_tickers, format_live_context
from config import (
    OLLAMA_MODEL,
    EMBEDDING_MODEL,
    CHROMA_DB_PATH,
    TOP_K_RESULTS,
)

# ── STRUCTURED RESEARCH PROMPT ──────────────────────────────
FINANCE_PROMPT = PromptTemplate(
    input_variables=["context", "live_data", "question"],
    template="""
You are a financial research assistant. You surface factual
data and structured analysis to help users understand stocks.

You are NOT a financial advisor. You must NEVER directly
tell someone to buy or sell a stock. Instead, present
balanced facts and let the user decide.

──────────────────────────────────────────────────────────
RESPONSE FORMAT — always use this structure for stock questions:
──────────────────────────────────────────────────────────

## [TICKER] — [Company Name] Research Summary

**At a Glance**
2-sentence overview of what the company does and its
current market position.

**Fundamental Picture**
Comment specifically on:
- Current price vs 52-week range (where in the range?)
- P/E ratio vs typical sector average (over/undervalued?)
- Revenue and profit margin trend
- Debt levels and ROE
- Dividend if applicable

**Technical Picture**
Interpret the signals:
- RSI reading and what it historically suggests
- MACD signal (bullish or bearish momentum)
- Moving average position (trend direction)
- Bollinger Band position (volatility context)
- Volume signal (conviction behind the move)

**Analyst View**
- State the analyst consensus clearly
- State the analyst price target vs current price
- Note any gap between current price and target

**Composite Research Score: [X]/100**
Explain what the score means in plain English based
on the breakdown provided. Do not hide the score.

**Factors That May Interest Buyers**
List exactly 3 factual, data-backed positives.
Each must reference a specific number from the live data.

**Factors That Suggest Caution**
List exactly 3 factual, data-backed risks or concerns.
Each must reference a specific number from the live data.

**Summary**
One balanced paragraph summarising the overall picture.
Do not lean bullish or bearish — present both sides equally.
End with: "This is research information only, not financial
advice. The decision is entirely yours."

──────────────────────────────────────────────────────────
For concept questions (not stock-specific), answer clearly
and factually from the knowledge base context provided.
──────────────────────────────────────────────────────────

Live Market Data (fetched right now):
{live_data}

Knowledge Base Context:
{context}

Question: {question}

Research Summary:
"""
)

DISCLAIMER = (
    "\n\n---\n"
    "⚠️ **Legal Disclaimer:** This output is generated by an AI "
    "research tool for informational purposes only. It does not "
    "constitute financial advice, a recommendation to buy or sell "
    "any security, or a solicitation of any investment decision. "
    "Past performance does not guarantee future results. Always "
    "consult a qualified, FCA-authorised financial advisor before "
    "making any investment decision."
)


def format_docs(docs: list) -> str:
    return "\n\n".join(doc.page_content for doc in docs)


def load_qa_chain():
    """Load embeddings, vector store and LLM. Returns (retriever, llm)."""
    embeddings = OllamaEmbeddings(model=EMBEDDING_MODEL)

    vectorstore = Chroma(
        persist_directory=CHROMA_DB_PATH,
        embedding_function=embeddings,
    )

    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": TOP_K_RESULTS},
    )

    llm = OllamaLLM(model=OLLAMA_MODEL, temperature=0.1)

    return retriever, llm


def ask(retriever_llm_tuple, question: str) -> dict:
    """
    Full pipeline:
    1. Detect tickers
    2. Fetch live data + technicals + composite score
    3. Retrieve knowledge base chunks
    4. Build structured prompt and invoke LLM
    5. Return answer + sources + metadata
    """
    retriever, llm = retriever_llm_tuple

    # Step 1 — detect tickers
    tickers = detect_tickers(question)

    # Step 2 — fetch live data (includes technicals and scores)
    live_data = format_live_context(tickers)

    # Step 3 — retrieve knowledge base
    source_docs = retriever.invoke(question)
    sources     = list({doc.metadata.get("source", "Unknown") for doc in source_docs})
    context     = format_docs(source_docs)

    # Step 4 — build and invoke prompt
    prompt = FINANCE_PROMPT.format(
        context=context,
        live_data=live_data,
        question=question,
    )
    raw_answer = llm.invoke(prompt)
    answer     = raw_answer + DISCLAIMER

    return {
        "answer":    answer,
        "sources":   sources,
        "tickers":   tickers,
        "live_data": live_data,
    }